name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    name: Rust Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy Check
        run: cargo clippy -- -D warnings
