name: Rust Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bc-cli-${{ matrix.os }}
          path: target/release/bc-cli${{ matrix.os == 'windows-latest' && '.exe' || '' }}
